<?php

namespace AppBundle\Repository;

/**
 * FighterSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FighterSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
