<?php

namespace AppBundle\Repository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    public function findComplete($id)
    {
        return $this
            ->createQueryBuilder('g')
            ->leftJoin('g.gameFighters','gf')
            ->leftJoin('gf.fighter','f')
            ->leftJoin('f.skills','s')
            ->addSelect('gf')
            ->addSelect('f')
            ->addSelect('s')
            ->where('g.id = :id')
            ->setParameter('id',$id)
            ->getQuery()
            ->getResult();
    }
}
