<?php

namespace AppBundle\Repository;

/**
 * GameFighterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameFighterRepository extends \Doctrine\ORM\EntityRepository
{
}
